export default {
  root: {
    backgroundColor: '#fff',
    border: '1px solid #ddd',
    borderRadius: '5px',
    padding: '0.5rem',
    position: 'relative',
    cursor: 'pointer',
    '&:hover > *': {
      opacity: '1',
    },
  },
  colors: {
    backgroundColor: '#dae1e4',
    height: '150px',
    width: '100%',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  title: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: '0',
    color: '#000',
    paddingTop: '0.5rem',
    fontSize: '1rem',
    position: 'relative',
  },
  emoji: {
    marginLeft: '0.5rem',
    fontSize: '1.5rem',
  },
  miniColor: {
    height: '25%',
    width: '20%',
    display: 'inline-block',
    margin: '0 auto',
    position: 'relative',
    marginBottom: '-3.5px',
  },
  deleteIcon: {
    boxSizing: 'content-box',
    backgroundColor: '#eb3d30',
    position: 'absolute',
    top: '0',
    right: '0',
    padding: '5px',
    zIndex: '1',
    opacity: '0',
    transition: 'all .4s ease-in-out',
    color: '#fff',
    width: '20px',
    height: '20px',
  },
};
