export default {
  login: 'do-Va',
  id: 57659479,
  node_id: 'MDQ6VXNlcjU3NjU5NDc5',
  avatar_url: 'https://avatars.githubusercontent.com/u/57659479?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/do-Va',
  html_url: 'https://github.com/do-Va',
  followers_url: 'https://api.github.com/users/do-Va/followers',
  following_url: 'https://api.github.com/users/do-Va/following{/other_user}',
  gists_url: 'https://api.github.com/users/do-Va/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/do-Va/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/do-Va/subscriptions',
  organizations_url: 'https://api.github.com/users/do-Va/orgs',
  repos_url: 'https://api.github.com/users/do-Va/repos',
  events_url: 'https://api.github.com/users/do-Va/events{/privacy}',
  received_events_url: 'https://api.github.com/users/do-Va/received_events',
  type: 'User',
  site_admin: false,
  name: 'doVa',
  company: 'doVa',
  blog: 'linkedin.com/in/doğukan-variş-21886a1a5',
  location: 'Istanbul',
  email: null,
  hireable: null,
  bio: "Even though it's a little late, he is a knowledge-hungry person who tries to learn new things and improve himself every day.",
  twitter_username: 'DogukanV',
  public_repos: 63,
  public_gists: 0,
  followers: 1,
  following: 2,
  created_at: '2019-11-12T08:11:32Z',
  updated_at: '2021-06-05T12:41:34Z',
};
